#!/bin/sh
./tray-test-fdo -w 22 -h 22 -c blue 2>&1 &
./tray-test-fdo -w 22 -h 22 -c green  2>&1 &
./tray-test-fdo -w 22 -h 22 -c magenta -gg 2>&1 &
sleep 1
./tray-test-fdo -w 22 -h 22 -c yellow 2>&1 &
./tray-test-fdo -w 22 -h 22 -c black 2>&1 &
